import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Volume2,Send,Plus,Trash2,FileCheck,ExternalLink} from 'lucide-react';
import {type Lang,type Words,say,services} from './catalogue';
import {useApp,Field,parse,local,serviceName,errors,type Row} from './shared';

const aiErrors:Record<string,Words>={
 aiNotConnected:['AI સેવા હજી જોડાયેલી નથી.','AI सेवा अभी जुड़ी नहीं है।','AI is not connected yet. The administrator must add the server API key.'],
 aiProvider:['AI સેવા હમણાં જવાબ આપી શકી નથી. ફરી પ્રયાસ કરો.','AI सेवा अभी उत्तर नहीं दे सकी। फिर कोशिश करें।','The AI provider could not complete the request. Try again shortly.'],
 aiQuota:['આજની અથવા હાલની AI મર્યાદા પૂરી થઈ. પછી પ્રયાસ કરો.','AI उपयोग की सीमा पूरी हुई। बाद में कोशिश करें।','An AI usage limit was reached. Try later or ask the administrator to review the quota.'],
 aiIncomplete:['જવાબ અધૂરો મળ્યો. ફરી પ્રયાસ કરો.','अधूरा उत्तर मिला। फिर कोशिश करें।','The provider returned an incomplete result. Please retry.'],
 aiConsent:['આગળ વધતાં પહેલાં પ્રક્રિયાની સંમતિ આપો.','आगे बढ़ने से पहले प्रोसेसिंग की सहमति दें।','Please accept the processing notice before using external AI or speech.'],
 sourceUnavailable:['મંજૂર સરકારી સ્રોત વાંચી શકાયો નથી. કચેરી પાસે ખાતરી કરો.','स्वीकृत सरकारी स्रोत पढ़ा नहीं जा सका। कार्यालय से पुष्टि करें।','No readable approved official source is available for this service. Ask the office to confirm requirements.'],
 fileMissing:['સંપૂર્ણ ફાઇલ પસંદ કરો અને ફરી મોકલો.','पूरी फ़ाइल चुनकर फिर भेजें।','Choose a complete file and upload it again.'],
 fileType:['માત્ર PDF, JPG કે PNG દસ્તાવેજ મોકલો.','केवल PDF, JPG या PNG दस्तावेज़ भेजें।','Upload a PDF, JPG or PNG document. The actual file content must match its type.'],
 fileSize:['ફાઇલ બહુ મોટી છે. 4 MBથી નાની ફાઇલ મોકલો.','फ़ाइल बड़ी है। 4 MB से छोटी फ़ाइल भेजें।','Use a document smaller than 4 MB and an image below 24 megapixels.'],
 speechUnclear:['વાણી સ્પષ્ટ નથી. ફરી બોલો અથવા લખો.','बोली स्पष्ट नहीं है। फिर बोलें या लिखें।','No clear speech was detected. Try again or type your question.'],
 voiceNotConnected:['આ ભાષાનો અવાજ ઉપલબ્ધ નથી. Cloud voice ગોઠવો.','इस भाषा की आवाज़ उपलब्ध नहीं है। Cloud voice सेट करें।','No matching voice is available. Configure cloud voice or use a device with this language installed.'],
 voiceLength:['અવાજ માટે જવાબ બહુ લાંબો છે. ટૂંકો જવાબ માગો.','आवाज़ के लिए उत्तर लंबा है। छोटा उत्तर माँगें।','This answer is too long for playback. Ask for a shorter answer.'],
 microphone:['માઇક્રોફોનની પરવાનગી અથવા બ્રાઉઝર સપોર્ટ તપાસો.','माइक्रोफ़ोन अनुमति या ब्राउज़र समर्थन जाँचें।','Check microphone permission and browser support. You can still type your question.'],
 chatChanged:['બીજા ટેબમાં ચેટ બદલાઈ. ઇતિહાસ ફરી ખોલો.','दूसरे टैब में चैट बदली। इतिहास फिर खोलें।','This conversation changed in another tab. Reopen it from history before retrying.'],
 cancelled:['વિનંતી રોકી. ભાષા કે પસંદગી બદલાઈ છે.','अनुरोध रोका गया। भाषा या चयन बदला है।','Request stopped. The language or selection changed.'],
};
const locale:Record<Lang,string>={gu:'gu-IN',hi:'hi-IN',en:'en-IN'};
const detect=(s:string,fallback:Lang):Lang=>/[\u0A80-\u0AFF]/.test(s)||/\b(mare|mane|tame|chhe|joie|kem)\b/i.test(s)?'gu':/[\u0900-\u097F]/.test(s)||/\b(mujhe|kaise|chahiye|batao)\b/i.test(s)?'hi':/\b(what|how|where|please|which)\b/i.test(s)?'en':fallback;

export function Help(){
 const {t,lang,data,login,post,refresh,confirm}=useApp();
 const [caps,setCaps]=useState<Row|null>(null),[id,setId]=useState<string|null>(null),[messages,setMessages]=useState<Row[]>([]),[text,setText]=useState(''),[temporary,setTemporary]=useState(false),[title,setTitle]=useState('');
 const [kind,setKind]=useState('certificate'),[consent,setConsent]=useState(false),[autoSpeak,setAutoSpeak]=useState(false),[pending,setPending]=useState(''),[error,setError]=useState(''),[errorLang,setErrorLang]=useState<Lang|null>(null),[recording,setRecording]=useState(false),[speaking,setSpeaking]=useState(false);
 const [service,setService]=useState(''),[documentType,setDocumentType]=useState(''),[expectedName,setExpectedName]=useState(''),[file,setFile]=useState<File|null>(null),[result,setResult]=useState<Row|null>(null);
 const abort=useRef<AbortController|null>(null),generation=useRef(0),speechGeneration=useRef(0),busy=useRef(false),audio=useRef<HTMLAudioElement|null>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recognition=useRef<any>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),list=useRef<HTMLDivElement>(null),csrf=useRef(data.csrf),currentLang=useRef(lang),alive=useRef(true);
 csrf.current=data.csrf;currentLang.current=lang;
 function stopAudio(){speechGeneration.current++;audio.current?.pause();audio.current=null;if('speechSynthesis' in window)window.speechSynthesis.cancel();setSpeaking(false);}
 function stopRecording(discard=false){if(timer.current)clearTimeout(timer.current);if(recorder.current){if(discard)recorder.current.onstop=null;if(recorder.current.state!=='inactive')recorder.current.stop();recorder.current=null;}if(recognition.current){recognition.current.abort();recognition.current=null;}stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setRecording(false);}
 function resetRequest(){generation.current++;abort.current?.abort();stopRecording(true);stopAudio();}
 useEffect(()=>{alive.current=true;const ac=new AbortController();fetch('./assistant.php',{signal:ac.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(setCaps).catch(()=>{if(!ac.signal.aborted)setError('unavailable');});return()=>{alive.current=false;ac.abort();generation.current++;abort.current?.abort();stopRecording(true);stopAudio();};},[]);
 useEffect(()=>{resetRequest();setError('');setErrorLang(null);},[lang]);
 useEffect(()=>{list.current?.scrollTo({top:list.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});},[messages,pending]);
 async function request(action:string,body:Row|FormData,responseLanguage=lang):Promise<Row|null>{
  if(busy.current)return null;busy.current=true;setPending(action);setError('');setErrorLang(responseLanguage);const seq=generation.current;const ac=new AbortController();abort.current=ac;const timeout=setTimeout(()=>ac.abort(),90000);
  try{const multipart=body instanceof FormData;if(multipart){body.set('action',action);body.set('lang',responseLanguage);body.set('consent',consent?'1':'');}
   const r=await fetch('./assistant.php',{method:'POST',headers:{'X-CSRF-Token':csrf.current,...(multipart?{}:{'Content-Type':'application/json'})},body:multipart?body:JSON.stringify({action,lang:responseLanguage,consent,...body}),signal:ac.signal});const d=await r.json();if(!r.ok)throw Error(d.error??'aiProvider');if(!alive.current||seq!==generation.current)return null;return d;
  }catch(e){if(alive.current&&seq===generation.current)setError((e as Error).name==='AbortError'?'unavailable':(e as Error).message);return null;}
  finally{clearTimeout(timeout);busy.current=false;if(alive.current)setPending('');abort.current=null;}
 }
 async function speak(message:Row){
  stopAudio();const speechSeq=speechGeneration.current;const speechLang=(['gu','hi','en'].includes(message.lang)?message.lang:lang) as Lang;const spoken=String(message.text).replace(/\[\d+\]/g,'');
  if(caps?.cloudVoice){const seq=generation.current;const r=await request('speak',{text:spoken},speechLang);if(!r||seq!==generation.current||speechSeq!==speechGeneration.current)return;const player=new Audio('data:audio/mpeg;base64,'+r.audio);audio.current=player;setSpeaking(true);player.onended=()=>setSpeaking(false);player.onerror=()=>{setSpeaking(false);setError('voiceNotConnected');};try{await player.play();}catch{setSpeaking(false);setError('voiceNotConnected');}return;}
  if(!consent){setError('aiConsent');return;}if(!('speechSynthesis' in window)){setError('voiceNotConnected');return;}
  const seq=generation.current;let voices=window.speechSynthesis.getVoices();if(!voices.length){await new Promise<void>(resolve=>{const done=()=>{clearTimeout(wait);window.speechSynthesis.removeEventListener('voiceschanged',done);resolve();};const wait=setTimeout(done,1200);window.speechSynthesis.addEventListener('voiceschanged',done);});voices=window.speechSynthesis.getVoices();}if(seq!==generation.current||speechSeq!==speechGeneration.current||!alive.current)return;const voice=voices.find(v=>v.lang.toLowerCase().startsWith(speechLang));if(!voice){setError('voiceNotConnected');return;}
  const utterance=new SpeechSynthesisUtterance(spoken);utterance.lang=locale[speechLang];utterance.voice=voice;utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(utterance);
 }
 async function record(){
  if(recording){stopRecording();return;}if(!data.user){login();return;}if(!consent){setError('aiConsent');return;}setError('');stopAudio();const seq=generation.current;
  if(caps?.transcription&&typeof MediaRecorder!=='undefined'&&navigator.mediaDevices?.getUserMedia){
   try{const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||seq!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
    const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error();const rec=new MediaRecorder(media,{mimeType:mime,audioBitsPerSecond:64000});recorder.current=rec;const chunks:BlobPart[]=[];
    rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onstop=async()=>{media.getTracks().forEach(t=>t.stop());setRecording(false);if(seq!==generation.current||!alive.current)return;const form=new FormData();form.set('audio',new Blob(chunks,{type:mime}),'question.'+(mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm'));const r=await request('transcribe',form);if(r){setText(r.text);setErrorLang(r.lang);}};
    rec.onerror=()=>{stopRecording(true);setError('microphone');};rec.start();setRecording(true);timer.current=setTimeout(()=>stopRecording(),30000);
   }catch{stopRecording(true);setError('microphone');}return;
  }
  const Recognition=(window as any).SpeechRecognition??(window as any).webkitSpeechRecognition;if(!Recognition){setError('microphone');return;}
  const rec=new Recognition();recognition.current=rec;rec.lang=locale[lang];rec.interimResults=false;rec.continuous=false;rec.onresult=(e:any)=>{if(seq===generation.current)setText(e.results[0][0].transcript);};rec.onerror=()=>{if(seq===generation.current)setError('microphone');};rec.onend=()=>{if(seq===generation.current)setRecording(false);};try{rec.start();setRecording(true);timer.current=setTimeout(()=>stopRecording(),30000);}catch{setError('microphone');}
 }
 async function send(e:React.FormEvent){e.preventDefault();if(!text.trim()||busy.current)return;if(!data.user){login();return;}stopRecording(true);const question=text.trim(),seq=generation.current;const r=await request('chat',{message:question,id:temporary?null:id,temporary,kind,context:temporary?messages.slice(-6).map(m=>({role:m.role,text:Array.from(String(m.text)).slice(0,2000).join('')})):[]},detect(question,lang));if(r){setId(r.id);if(!id)setTitle(question.slice(0,60));setMessages(temporary?[...messages,...r.messages]:r.messages);setText('');await refresh();if(autoSpeak&&seq===generation.current)await speak(r.messages[r.messages.length-1]);}}
 function newChat(){resetRequest();setId(null);setMessages([]);setTitle('');setError('');}
 const documentServices=data.services.filter(s=>s.enabled&&data.offices.some(o=>o.id===s.office_id&&o.verified));
 return <><div className="page-heading"><span className="eyebrow">{t('તમારી ભાષામાં સહાય','आपकी भाषा में सहायता','HELP IN YOUR LANGUAGE')}</span><h1>{t('પૂછો. બોલો. તૈયારી કરો.','पूछें। बोलें। तैयार हों।','Ask. Speak. Arrive prepared.')}</h1><p>{t('સરકારી સ્રોત, વૉઇસ અને દસ્તાવેજની પ્રાથમિક તપાસ.','सरकारी स्रोत, आवाज़ और दस्तावेज़ की शुरुआती जाँच।','Official sources, voice and preliminary document checks.')}</p></div>
 <div className="assistant-status panel"><span className={'badge '+(caps?.ai?'':'amber')}>{caps===null?t('જોડાણ તપાસીએ છીએ','कनेक्शन जाँच रहे हैं','Checking connection'):caps.ai?t('AI ગોઠવેલું','AI कॉन्फ़िगर है','AI configured'):t('સ્થાનિક માર્ગદર્શક · AI જોડાયેલ નથી','स्थानीय मार्गदर्शक · AI नहीं जुड़ा','Local guide · AI not connected')}</span><span className="small-text">{caps?.cloudVoice?t('Cloud voice ગોઠવેલું','Cloud voice कॉन्फ़िगर है','Cloud voice configured'):t('અવાજ માટે ઉપકરણની ભાષાનો સપોર્ટ જરૂરી','आवाज़ के लिए डिवाइस में भाषा का समर्थन चाहिए','Device voice availability varies by language')}</span><p>{t('પ્રશ્નની ભાષા આપમેળે ઓળખાશે. શંકા હોય તો વેબસાઇટની પસંદ કરેલી ભાષા વપરાશે.','प्रश्न की भाषा अपने आप पहचानी जाएगी। संदेह में वेबसाइट की भाषा उपयोग होगी।','Replies follow your question’s detected language; ambiguous questions use the website language.')}</p><label className="check-row"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(!e.target.checked){resetRequest();setAutoSpeak(false);}}}/>{t('હું સમજું છું: AI માટે પ્રશ્નો, તાજેતરની ચેટ, ઑડિયો અને પસંદ કરેલા દસ્તાવેજ Googleને મોકલાશે. બ્રાઉઝર વૉઇસ તેનો પ્રદાતા વાપરી શકે.','मैं समझता/समझती हूँ: AI के लिए प्रश्न, हाल की चैट, ऑडियो और चुने दस्तावेज़ Google को भेजे जाएँगे। ब्राउज़र वॉइस उसका प्रदाता उपयोग कर सकती है।','I understand: AI requests send questions, recent conversation, recorded audio or selected documents to Google. Browser speech may use its browser provider.')}</label></div>
 {error&&<div className="notice warning" role="alert">{say(aiErrors[error]??errors[error]??errors.unavailable,errorLang??lang)} <button className="text-button" onClick={()=>setError('')}>{t('બંધ કરો','बंद करें','Dismiss')}</button></div>}
 <div className="chat-grid"><aside className="panel chat-history"><button className="btn full" disabled={!!pending} onClick={newChat}><Plus size={17}/>{t('નવી વાતચીત','नई बातचीत','New conversation')}</button><label className="check-row"><input type="checkbox" checked={temporary} disabled={!!pending} onChange={e=>{setTemporary(e.target.checked);newChat();}}/>{t('અસ્થાયી ચેટ','अस्थायी चैट','Temporary chat')}</label><h3>{t('ઇતિહાસ','इतिहास','History')}</h3>{data.chats.map(c=><div className="chat-entry" key={c.id}><button disabled={!!pending} className={id===c.id?'selected':''} onClick={()=>{resetRequest();setId(c.id);setTemporary(false);setMessages(parse(c.messages));setTitle(c.title);}}>{c.title}</button><button disabled={!!pending} className="icon" aria-label={t('ચેટ કાઢો','चैट हटाएँ','Delete chat')} onClick={()=>confirm(t('વાતચીત કાઢવી છે?','बातचीत हटाएँ?','Delete conversation?'),t('આ ક્રિયા પાછી ફેરવી શકાશે નહીં.','यह कार्य वापस नहीं होगा।','This cannot be undone.'),async()=>{const r=await post('deleteChat',{id:c.id});if(r&&id===c.id)newChat();return r;})}><Trash2 size={16}/></button></div>)}{!data.user&&<button className="btn" onClick={login}>{t('સાઇન ઇન','साइन इन','Sign in')}</button>}</aside>
 <section className="panel chat-panel ai-chat"><div className="chat-header"><strong>QueueLess {t('સહાયક','सहायक','assistant')}</strong><span className="badge">{temporary?t('સાચવાશે નહીં','सहेजा नहीं जाएगा','Not saved'):t('ચેટ ઇતિહાસ','चैट इतिहास','Chat history')}</span></div><div className="assistant-controls"><Field label={t('સેવાનો વિષય','सेवा का विषय','Service topic')}><select value={kind} disabled={!!pending} onChange={e=>setKind(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{say(s.name,lang)}</option>)}</select></Field><label className="check-row"><input type="checkbox" checked={autoSpeak} onChange={e=>setAutoSpeak(e.target.checked)}/>{t('જવાબ બોલીને આપો','उत्तर बोलकर सुनाएँ','Speak answers')}</label></div>
 {id&&!temporary&&<form className="rename-form" onSubmit={async e=>{e.preventDefault();await post('renameChat',{id,title});}}><input aria-label={t('ચેટનું નામ','चैट का नाम','Conversation title')} value={title} maxLength={100} onChange={e=>setTitle(e.target.value)} required/><button className="text-button" disabled={!!pending}>{t('સાચવો','सहेजें','Save')}</button></form>}
 <div ref={list} className="messages" aria-live="polite">{!messages.length&&<div className="chat-welcome"><h2>{t('શું જાણવું છે?','क्या जानना चाहते हैं?','What would you like to know?')}</h2><p>{t('યોજના, દસ્તાવેજ અથવા તમારા ટોકન વિશે પૂછો.','योजना, दस्तावेज़ या अपने टोकन के बारे में पूछें।','Ask about a scheme, a document or your token.')}</p><button className="btn" onClick={()=>setText(t('મારા ટોકનનો રાહનો સમય?','मेरे टोकन का प्रतीक्षा समय?','What is the wait for my token?'))}>{t('મારો રાહનો સમય','मेरा प्रतीक्षा समय','My waiting estimate')}</button></div>}{messages.map((m,i)=><div className={'message '+m.role} key={i}><div>{m.text}{m.role==='assistant'&&<><div className="answer-meta"><span>{m.mode==='ai'?t('AI જવાબ · સ્ત્રોત તપાસો','AI उत्तर · स्रोत देखें','AI answer · check sources'):t('સ્થાનિક માર્ગદર્શન','स्थानीय मार्गदर्शन','Local guidance')}</span><button className="icon" disabled={!!pending} aria-label={t('જવાબ સાંભળો','उत्तर सुनें','Listen to answer')} onClick={()=>speak(m)}><Volume2 size={17}/></button></div><SourceList sources={m.sources??[]}/></>}</div></div>)}{pending==='chat'&&<div className="skeleton assistant-skeleton" aria-label={t('જવાબ તૈયાર થાય છે','उत्तर तैयार हो रहा है','Preparing answer')}/>}</div>
 <form className="chat-compose" onSubmit={send}><button type="button" className={'btn '+(recording?'recording':'')} disabled={!!pending} onClick={record} aria-label={recording?t('રેકોર્ડિંગ રોકો','रिकॉर्डिंग रोकें','Stop recording'):t('પ્રશ્ન બોલો','प्रश्न बोलें','Speak a question')}>{recording?<Square size={18}/>:<Mic size={18}/>}</button><input value={text} onChange={e=>setText(e.target.value)} aria-label={t('તમારો પ્રશ્ન','आपका प्रश्न','Your question')} placeholder={t('અહીં પૂછો…','यहाँ पूछें…','Ask here…')} maxLength={2000} required/><button className="btn primary" disabled={!!pending||!text.trim()} aria-label={t('મોકલો','भेजें','Send')}><Send size={18}/></button></form>{recording&&<p role="status" className="small-text center">{t('સાંભળીએ છીએ · મહત્તમ 30 સેકન્ડ','सुन रहे हैं · अधिकतम 30 सेकंड','Listening · up to 30 seconds')}</p>}{pending&&pending!=='chat'&&<p role="status" className="small-text center">{t('પ્રક્રિયા ચાલુ છે…','प्रक्रिया जारी है…','Processing…')}</p>}{speaking&&<button className="text-button" onClick={stopAudio}>{t('અવાજ રોકો','आवाज़ रोकें','Stop speaking')}</button>}<p className="small-text muted center">{t('બોલેલો પ્રશ્ન મોકલતા પહેલાં તપાસો. ચેટ બુકિંગ બદલતી નથી.','बोला हुआ प्रश्न भेजने से पहले जाँचें। चैट बुकिंग नहीं बदलती।','Review the transcript before sending. Chat cannot change bookings.')}</p></section></div>
 <section className="panel document-check"><div className="section-heading"><h2><FileCheck size={22}/>{t('દસ્તાવેજની તૈયારી તપાસો','दस्तावेज़ की तैयारी जाँचें','Check document readiness')}</h2><span className="badge amber">{t('પ્રાથમિક તપાસ','शुरुआती जाँच','Preliminary check')}</span></div><p className="muted">{t('વાંચી શકાય છે કે નહીં, જરૂરી વિગતો અને દેખાતી તારીખ તપાસો. આ સરકારી પ્રમાણિકતા ચકાસણી કે મંજૂરી નથી.','पठनीयता, आवश्यक विवरण और दिखाई देने वाली तारीख जाँचें। यह सरकारी प्रामाणिकता जाँच या स्वीकृति नहीं है।','Check readability, required details and visible dates. This does not authenticate the document or approve an application.')}</p>
 <form className="stack" onSubmit={async e=>{e.preventDefault();if(!data.user){login();return;}if(!file){setError('fileMissing');return;}if(file.size>4*1024*1024){setError('fileSize');return;}setResult(null);const form=new FormData();form.set('document',file);form.set('service',service);form.set('documentType',documentType);form.set('expectedName',expectedName);const r=await request('document',form);if(r)setResult(r);}}><fieldset className="stack assistant-fields" disabled={!!pending}><div className="two-col"><Field label={t('કચેરી અને સેવા','कार्यालय और सेवा','Office and service')}><select value={service} onChange={e=>{setService(e.target.value);setResult(null);}} required><option value="">{t('પસંદ કરો','चुनें','Choose')}</option>{documentServices.map(s=><option key={s.id} value={s.id}>{local(data.offices.find(o=>o.id===s.office_id)?.name,lang)} · {serviceName(s.kind,lang)}</option>)}</select></Field><Field label={t('દસ્તાવેજનું નામ','दस्तावेज़ का नाम','Document type')}><input value={documentType} onChange={e=>{setDocumentType(e.target.value);setResult(null);}} maxLength={120} required placeholder={t('જેમ કે આવકનો દાખલો','जैसे आय प्रमाणपत्र','For example, income certificate')}/></Field></div><Field label={t('અરજીમાં આપેલું નામ · વૈકલ્પિક','आवेदन में दिया नाम · वैकल्पिक','Name entered on the application · optional')}><input value={expectedName} onChange={e=>{setExpectedName(e.target.value);setResult(null);}} maxLength={100} autoComplete="off"/></Field><Field label={t('PDF, JPG અથવા PNG · મહત્તમ 4 MB','PDF, JPG या PNG · अधिकतम 4 MB','PDF, JPG or PNG · maximum 4 MB')}><input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{setFile(e.target.files?.[0]??null);setResult(null);}} required/></Field><p className="small-text muted">{t('સાઇટ ફાઇલ કે તપાસનું પરિણામ સાચવતી નથી. ફાઇલ Googleને મોકલાશે; તેની ડેટા સંગ્રહની શરતો લાગુ પડે છે.','साइट फ़ाइल या जाँच परिणाम नहीं सहेजती। चुनी फ़ाइल प्रोसेसिंग के लिए Google को भेजी जाएगी।','This site does not retain the file or inspection result. The selected file is sent to Google for processing; its retention terms apply.')}</p><button className="btn primary" disabled={!!pending||!caps?.ai||!consent}>{pending==='document'?t('તપાસ ચાલુ…','जाँच जारी…','Checking…'):t('દસ્તાવેજ તપાસો','दस्तावेज़ जाँचें','Check document')}</button>{!caps?.ai&&<p className="notice">{say(aiErrors.aiNotConnected,lang)}</p>}</fieldset></form>
 {result&&<div className="document-result" aria-live="polite"><h3>{result.status==='checked'?t('પ્રાથમિક તપાસ પૂર્ણ','शुरुआती जाँच पूरी','Preliminary checks completed'):result.status==='correction'?t('સુધારા તપાસો','सुधार देखें','Review these corrections'):t('અધિકારીની તપાસ જરૂરી','अधिकारी की जाँच आवश्यक','Officer review required')}</h3><p>{say(result.summary,lang)}</p><p className="notice warning">{t('દસ્તાવેજ ખરેખર સરકારી છે તેની ખાતરી થયેલી નથી.','दस्तावेज़ की सरकारी प्रामाणिकता सत्यापित नहीं हुई है।','Document authenticity has not been verified.')}</p>{!result.rulesCurrent&&<p className="notice warning">{t('હાલના સત્તાવાર નિયમોની ખાતરી થઈ નથી. કચેરી પાસે તપાસો.','वर्तमान आधिकारिक नियमों की पुष्टि नहीं हुई। कार्यालय से जाँचें।','Current official requirements could not be confirmed. Check with the office.')}</p>}{result.issues.map((issue:Row,i:number)=><article className="document-issue" key={i}><strong>{say(issue.field,lang)}</strong><p>{say(issue.message,lang)}</p><p><strong>{t('શું કરવું','क्या करें','What to do')}: </strong>{say(issue.correction,lang)}</p></article>)}<SourceList sources={result.sources}/><button className="btn" disabled={!!pending} onClick={()=>speak({text:[say(result.summary,lang),...result.issues.map((i:Row)=>say(i.correction,lang))].join('. '),lang})}><Volume2 size={17}/>{t('પરિણામ સાંભળો','परिणाम सुनें','Listen to results')}</button><button className="text-button" onClick={()=>setResult(null)}>{t('પરિણામ સાફ કરો','परिणाम साफ़ करें','Clear results')}</button></div>}</section>
 </>;
}
function SourceList({sources}:{sources:Row[]}){const {t,lang}=useApp();if(!sources.length)return null;return <div className="assistant-sources"><strong>{t('સત્તાવાર સ્રોત','आधिकारिक स्रोत','Official sources')}</strong>{sources.map((s,i)=><div key={s.url}><a href={s.url} target="_blank" rel="noreferrer">[{i+1}] {s.title} <ExternalLink size={12}/></a><small>{s.stale?t('જૂની નકલ · ફરી તપાસ થઈ નથી','पुरानी प्रति · फिर जाँच नहीं हुई','Stale copy · refresh unavailable'):t('મેળવ્યું','प्राप्त किया','Retrieved')} {new Date(s.retrievedAt).toLocaleString(locale[lang],{timeZone:'Asia/Kolkata'})} IST</small></div>)}</div>;}
