import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {CalendarDays,Ticket,Layers,MessageCircle,UserRound,Monitor,ShieldCheck,Clock,LogOut,Menu,X,RefreshCw,Languages,Bell} from 'lucide-react';
import {type Lang,say} from './catalogue';
import {Context,type Snapshot,type Row,parse,local,serviceName,time,date,days,errors,Field,active} from './shared';
import {Plan,Tokens,Schemes,Help,Profile} from './citizen';
import {Desk,Admin} from './staff';
import './style.css';
const empty:Snapshot={user:null,offices:[],services:[],counters:[],visits:[],summaries:{},desk:[],metrics:{},audit:[],members:[],notifications:[],chats:[],updated:0,csrf:'',otpAvailable:false,smsAvailable:false};
function App(){
 const [data,setData]=useState<Snapshot>(empty),[lang,setLang]=useState<Lang>(()=>(localStorage.getItem('ql-lang') as Lang)||'gu'),[view,setView]=useState('home');
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[menu,setMenu]=useState(false),[haptics,setHaptic]=useState(localStorage.getItem('ql-haptics')==='true');
 const [modal,setModal]=useState<Row|null>(null),[authMode,setAuthMode]=useState('login'),[otpSent,setOtpSent]=useState(false),[phone,setPhone]=useState('+91'),[recovery,setRecovery]=useState('');
 const [booking,setBooking]=useState<Row|null>(null),[day,setDay]=useState(days()[0]),[chosen,setChosen]=useState<number|null>(null),[slots,setSlots]=useState<Row[]>([]),[slotsLoading,setSlotsLoading]=useState(false),[slotError,setSlotError]=useState('');
 const csrf=useRef(''),generation=useRef(0),refreshing=useRef<Promise<void>|null>(null),dialog=useRef<HTMLDialogElement>(null),inFlight=useRef(false),notificationSeen=useRef<string|null|undefined>(undefined);
 const t=(gu:string,hi:string,en:string)=>say([gu,hi,en],lang);
 function go(v:string){setView(v);location.hash=v;setMenu(false);window.scrollTo(0,0);}
 function errorText(code:string){return say(errors[code]??errors.unavailable,lang);}
 async function refresh(force=false):Promise<void>{
  if(refreshing.current){if(!force)return refreshing.current;await refreshing.current;}
  const gen=generation.current;
  const request=(async()=>{
  try{const r=await fetch('./api.php',{cache:'no-store',signal:AbortSignal.timeout(12000)});const d:any=await r.json();if(!r.ok)throw Error(d.error);if(gen===generation.current){csrf.current=d.csrf;setData(d);setError('');}}
  catch(e){if(gen===generation.current)setError((e as Error).message);}finally{refreshing.current=null;setLoading(false);}
  })();refreshing.current=request;return request;
 }
 async function post(action:string,values:Row={}){
  if(inFlight.current)return null;inFlight.current=true;setBusy(true);generation.current++;
  try{const r=await fetch('./api.php',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf.current},body:JSON.stringify({action,...values}),signal:AbortSignal.timeout(25000)});const d:any=await r.json();if(d.csrf)csrf.current=d.csrf;if(!r.ok)throw Error(d.error);setError('');if(haptics&&navigator.vibrate)navigator.vibrate(15);await refresh(true);return d;}
  catch(e){setMessage(errorText((e as Error).message));return null;}finally{setBusy(false);inFlight.current=false;}
 }
 useEffect(()=>{const onHash=()=>setView(['home','token','schemes','help','profile','desk','admin'].includes(location.hash.slice(1))?location.hash.slice(1):'home');onHash();window.addEventListener('hashchange',onHash);refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!inFlight.current)refresh();},5000);const visible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);window.removeEventListener('hashchange',onHash);document.removeEventListener('visibilitychange',visible);};},[]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('ql-lang',lang);},[lang]);
 useEffect(()=>{if(!data.updated)return;const n=data.notifications[0];if(notificationSeen.current!==undefined&&n&&n.id!==notificationSeen.current&&!n.read_at)setMessage(local(n.message,lang));notificationSeen.current=n?.id??null;},[data.notifications]);
 useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),6500);return()=>clearTimeout(id);},[message]);
 useEffect(()=>{if(modal&&!dialog.current?.open)dialog.current?.showModal();if(!modal&&dialog.current?.open)dialog.current.close();},[modal]);
 useEffect(()=>{
  if(modal?.kind!=='booking'||!booking)return;const ac=new AbortController();setSlotsLoading(true);setSlotError('');setChosen(null);
  fetch(`./api.php?action=slots&service=${encodeURIComponent(booking.service.id)}&day=${day}`,{signal:ac.signal,cache:'no-store'}).then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);return d;}).then((d:any)=>setSlots(d.slots.filter((s:Row)=>!booking.earlier||s.arrival<booking.visit.arrival))).catch(e=>{if(e.name!=='AbortError')setSlotError(e.message);}).finally(()=>{if(!ac.signal.aborted)setSlotsLoading(false);});return()=>ac.abort();
 },[booking,day,modal?.kind]);
 function login(){setAuthMode('login');setOtpSent(false);setModal({kind:'auth'});}
 function book(service:Row,visit?:Row,earlier=false){setBooking({service,visit,earlier,id:visit?.id??crypto.randomUUID()});setDay(visit?new Date(Number(visit.arrival)+330*60000).toISOString().slice(0,10):days()[0]);setChosen(null);setModal({kind:'booking'});}
 function confirm(title:string,body:string,run:()=>Promise<unknown>){setModal({kind:'confirm',title,body,run});}
 async function submitAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const action=authMode==='phone'?(otpSent?'otpCheck':'otpSend'):authMode;const result=await post(action,{...f,phone});if(!result)return;if(action==='otpSend'){setOtpSent(true);return;}if(result.recovery){setRecovery(result.recovery);setModal({kind:'recovery'});}else if(booking){setModal({kind:'booking'});}else setModal(null);}
 const nav=[['home',CalendarDays,t('મુલાકાત ગોઠવો','मुलाकात तय करें','Plan Visit')],['token',Ticket,t('મારું ટોકન','मेरा टोकन','My Token')],['schemes',Layers,t('યોજનાઓ','योजनाएँ','Schemes')],['help',MessageCircle,t('સહાય','सहायता','Help')],['profile',UserRound,t('મારી પ્રોફાઇલ','मेरी प्रोफ़ाइल','Profile')]] as const;
 const isStaff=['admin','officer'].includes(data.user?.role??'');
 const office=booking?data.offices.find(o=>o.id===booking.service.office_id):null;
 const setHaptics=(v:boolean)=>{setHaptic(v);localStorage.setItem('ql-haptics',String(v));};
 return <Context.Provider value={{lang,t,data,busy,post,go,login,book,toast:setMessage,confirm,refresh,haptics,setHaptics}}><div className="app-shell">
 <aside className={'sidebar '+(menu?'open':'')}><a className="brand" href="#home"><span className="brand-icon"><Clock/></span><span>QueueLess<small>GUJARAT</small></span></a><p className="nav-label">{t('નાગરિક સેવાઓ','नागरिक सेवाएँ','CITIZEN SERVICES')}</p><nav>{nav.map(([id,Icon,label])=><button key={id} className={view===id?'selected':''} onClick={()=>go(id)}><Icon size={20}/>{label}{id==='token'&&data.visits.filter(active).length>0&&<span className="count">{data.visits.filter(active).length}</span>}</button>)}</nav><div className="sidebar-note"><ShieldCheck/><strong>{t('તમારો સમય સુરક્ષિત','आपका समय सुरक्षित','Your time stays yours')}</strong><p>{t('તમારી સંમતિ વિના આગમનનો સમય વહેલો નહીં થાય.','आपकी अनुमति बिना आगमन पहले नहीं होगा।','Your arrival never moves earlier without your approval.')}</p></div>{isStaff&&<nav className="staff-nav"><button className={view==='desk'?'selected':''} onClick={()=>go('desk')}><Monitor size={20}/>{t('અધિકારી ડેસ્ક','अधिकारी डेस्क','Officer desk')}</button>{data.user?.role==='admin'&&<button className={view==='admin'?'selected':''} onClick={()=>go('admin')}><ShieldCheck size={20}/>{t('વહીવટ','प्रशासन','Administration')}</button>}</nav>}<div className="sidebar-bottom"><span className="avatar">{data.user?.name?.slice(0,1)??'Q'}</span><div><strong>{data.user?.name??t('મુલાકાતી','अतिथि','Guest')}</strong><small>{data.user?t('સાઇન ઇન થયેલ','साइन इन किया','Signed in'):t('જાહેર માહિતી જુઓ','सार्वजनिक जानकारी देखें','Browse freely')}</small></div></div></aside>
 <div className="workspace"><header className="topbar"><button className="icon mobile" aria-label={t('મેનુ','मेनू','Menu')} onClick={()=>setMenu(!menu)}><Menu/></button><span className="breadcrumb">QueueLess <span>/</span> {nav.find(n=>n[0]===view)?.[2]??(view==='desk'?t('અધિકારી ડેસ્ક','अधिकारी डेस्क','Officer desk'):t('વહીવટ','प्रशासन','Administration'))}</span><div className="top-actions"><label className="language"><Languages size={18}/><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="gu">ગુજરાતી</option><option value="hi">हिन्दी</option><option value="en">English</option></select></label><button className="btn small" onClick={()=>data.user?go('profile'):login()}>{data.user?t('મારું ખાતું','मेरा खाता','My account'):t('સાઇન ઇન','साइन इन','Sign in')}</button></div></header>
 <main><div className={'sync '+(error?'stale':'')}><span className="sync-dot"/>{error?t('અપડેટ મળ્યું નથી · છેલ્લી માહિતી બતાવીએ છીએ','अपडेट नहीं मिला · पिछली जानकारी दिखाई जा रही है','Update unavailable · showing the last received data'):t('દર 5 સેકન્ડે અપડેટ','हर 5 सेकंड में अपडेट','Updates every 5 seconds')}{data.updated>0&&<span>{t('છેલ્લું','अंतिम','Last received')}: {time(data.updated,lang)} IST</span>}<button className="icon" onClick={()=>refresh()} aria-label={t('રિફ્રેશ','रीफ्रेश','Refresh')}><RefreshCw size={16}/></button></div>
 {error&&<div className="notice warning" role="alert">{errorText(error)} {error==='setupRequired'&&<a href="./install.php">{t('સેટઅપ ખોલો','सेटअप खोलें','Open setup')}</a>}</div>}
 {loading?<div className="skeleton-layout"><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div>:<>{view==='home'&&<Plan/>}{view==='token'&&<Tokens/>}{view==='schemes'&&<Schemes/>}{view==='help'&&<Help/>}{view==='profile'&&<Profile/>}{view==='desk'&&(isStaff?<Desk/>:<div className="empty">{t('અધિકારી ખાતાથી સાઇન ઇન કરો.','अधिकारी खाते से साइन इन करें।','Sign in with an assigned officer account.')}</div>)}{view==='admin'&&(data.user?.role==='admin'?<Admin/>:<div className="empty">{t('વહીવટકર્તાની પરવાનગી જરૂરી છે.','प्रशासक की अनुमति आवश्यक है।','Administrator access is required.')}</div>)}</>}
 <footer><span>QueueLess Gujarat</span><span>{t('સ્વતંત્ર મુલાકાત વ્યવસ્થાપન · સત્તાવાર સરકારી પોર્ટલ નથી','स्वतंत्र मुलाकात प्रबंधन · आधिकारिक सरकारी पोर्टल नहीं','Independent visit management · Not an official government portal')}</span></footer></main></div>
 <nav className="mobile-nav">{nav.map(([id,Icon,label])=><button key={id} className={view===id?'selected':''} onClick={()=>go(id)}><Icon size={20}/><span>{label}</span></button>)}</nav>
 <dialog ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setModal(null);}}><button className="icon close" disabled={busy} onClick={()=>setModal(null)} aria-label={t('બંધ કરો','बंद करें','Close')}><X/></button>
 {modal?.kind==='auth'&&<><span className="eyebrow">QueueLess Gujarat</span><h2>{authMode==='register'?t('તમારું ખાતું બનાવો','अपना खाता बनाएँ','Create your account'):authMode==='recover'?t('ખાતું પાછું મેળવો','खाता वापस पाएँ','Recover your account'):t('ફરી સ્વાગત છે','फिर स्वागत है','Welcome back')}</h2><p className="muted">{t('બુકિંગ અને ઇતિહાસ તમારા ખાતામાં સાચવાશે.','बुकिंग और इतिहास आपके खाते में सहेजे जाएँगे।','Your bookings and history stay with your account.')}</p><div className="tabs"><button onClick={()=>setAuthMode('login')} className={authMode==='login'?'selected':''}>{t('ઈમેલ','ईमेल','Email')}</button>{data.otpAvailable&&<button className={authMode==='phone'?'selected':''} onClick={()=>setAuthMode('phone')}>{t('મોબાઇલ OTP','मोबाइल OTP','Mobile OTP')}</button>}<button className={authMode==='register'?'selected':''} onClick={()=>setAuthMode('register')}>{t('નવું ખાતું','नया खाता','Register')}</button></div><form onSubmit={submitAuth} className="stack">
 {authMode==='phone'?<><Field label={t('મોબાઇલ નંબર','मोबाइल नंबर','Mobile number')}><input value={phone} onChange={e=>{setPhone(e.target.value);setOtpSent(false);}} type="tel" autoComplete="tel" required placeholder="+919876543210" pattern="\+91[6-9][0-9]{9}"/></Field>{otpSent&&<Field label={t('SMS કોડ','SMS कोड','SMS code')}><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{4,10}" required/></Field>}</>:<><Field label={t('ઈમેલ','ईमेल','Email')}><input name="email" type="email" autoComplete="email" required/></Field>{authMode==='register'&&<Field label={t('તમારું નામ','आपका नाम','Your name')}><input name="name" autoComplete="name" maxLength={100} required/></Field>}{authMode==='recover'&&<Field label={t('રિકવરી કોડ','रिकवरी कोड','Recovery code')}><input name="recovery" autoComplete="off" required/></Field>}<Field label={t('પાસવર્ડ · ઓછામાં ઓછા 12 અક્ષર','पासवर्ड · कम से कम 12 अक्षर','Password · at least 12 characters')}><input name="password" type="password" autoComplete={authMode==='login'?'current-password':'new-password'} minLength={12} maxLength={128} required/></Field></>}
 <button className="btn primary" disabled={busy}>{busy?t('પ્રક્રિયા ચાલુ…','प्रक्रिया जारी…','Working…'):authMode==='phone'&&!otpSent?t('કોડ મોકલો','कोड भेजें','Send code'):authMode==='register'?t('ખાતું બનાવો','खाता बनाएँ','Create account'):authMode==='recover'?t('પાસવર્ડ બદલો','पासवर्ड बदलें','Reset password'):t('સાઇન ઇન','साइन इन','Sign in')}</button></form>{authMode!=='phone'&&<button className="text-button" onClick={()=>setAuthMode('recover')}>{t('પાસવર્ડ ભૂલાઈ ગયો? રિકવરી કોડ વાપરો','पासवर्ड भूल गए? रिकवरी कोड उपयोग करें','Forgot password? Use your recovery code')}</button>}{!data.otpAvailable&&<p className="small-text muted">{t('મોબાઇલ OTP હજી જોડાયેલ નથી. ઈમેલ અને પાસવર્ડથી પ્રવેશ કરો.','मोबाइल OTP अभी जुड़ा नहीं है। ईमेल और पासवर्ड से प्रवेश करें।','Mobile OTP is not connected yet. Use email and password.')}</p>}</>}
 {modal?.kind==='recovery'&&<><h2>{t('રિકવરી કોડ સાચવો','रिकवरी कोड सहेजें','Save your recovery code')}</h2><p>{t('પાસવર્ડ ભૂલાય તો આ કોડ જરૂરી છે. સુરક્ષિત જગ્યાએ સાચવો; ફરી દેખાશે નહીં.','पासवर्ड भूलने पर यह कोड चाहिए। सुरक्षित रखें; दोबारा नहीं दिखेगा।','You need this code if you forget your password. Store it safely; it will not be shown again.')}</p><code className="recovery-code">{recovery}</code><button className="btn primary" onClick={()=>{setRecovery('');setModal(booking?{kind:'booking'}:null);}}>{t('મેં સાચવી લીધો','मैंने सहेज लिया','I have saved it')}</button></>}
 {modal?.kind==='booking'&&booking&&<><span className="eyebrow">{booking.visit?t('સમય બદલો','समय बदलें','RESCHEDULE'):t('મુલાકાત બુક કરો','मुलाकात बुक करें','RESERVE A VISIT')}</span><h2>{serviceName(booking.service.kind,lang)}</h2><p>{local(office?.name,lang)}</p>{booking.visit&&<div className="notice">{t('હાલનો સમય','वर्तमान समय','Current time')}: {date(booking.visit.arrival,lang)} · {time(booking.visit.arrival,lang)}. {t('નવો સમય બુક થાય ત્યાં સુધી આ સમય સુરક્ષિત છે.','नया समय बुक होने तक यह समय सुरक्षित है।','This time stays reserved until the replacement is secured.')}</div>}<Field label={t('કચેરી','कार्यालय','Office')}><select value={booking.service.id} onChange={e=>setBooking({...booking,service:data.services.find(s=>s.id===e.target.value)})}>{data.services.filter(s=>s.kind===booking.service.kind&&s.enabled&&data.offices.some(o=>o.id===s.office_id&&o.verified)).map(s=><option key={s.id} value={s.id}>{local(data.offices.find(o=>o.id===s.office_id)?.name,lang)}</option>)}</select></Field><Field label={t('તારીખ','तारीख','Date')}><select value={day} onChange={e=>setDay(e.target.value)}>{days().map(d=><option key={d} value={d}>{date(d,lang)}</option>)}</select></Field><p className="muted small-text">{t('બધા સમય ભારતીય સમય પ્રમાણે · 15 મિનિટની આગમન વિન્ડો','सभी समय भारतीय समय अनुसार · 15 मिनट की आगमन अवधि','All times IST · 15-minute arrival window')}</p>
 {slotsLoading?<div className="skeleton slot-skeleton"/>:slotError?<p role="alert" className="notice warning">{errorText(slotError)}</p>:<div className="slots">{slots.map(s=><button key={s.arrival} disabled={!s.remaining} className={chosen===s.arrival?'selected':''} onClick={()=>setChosen(s.arrival)}>{time(s.arrival,lang)}<small>{s.remaining?t('ઉપલબ્ધ','उपलब्ध','Available'):t('ભરાયેલ','भरा','Full')}</small></button>)}{!slots.length&&<p>{t('આ દિવસે સમય ઉપલબ્ધ નથી. બીજી તારીખ પસંદ કરો.','इस दिन समय उपलब्ध नहीं है। दूसरी तारीख चुनें।','No slots on this day. Choose another date.')}</p>}</div>}
 {chosen&&<div className="notice">{t('પહોંચવાનો સમય','पहुँचने का समय','Arrive between')} <strong>{time(chosen,lang)}–{time(chosen+15*60000,lang)}</strong></div>}<p className="small-text muted">{t('ટોકન મફત છે. આગમનના 60 મિનિટ પહેલાં સમય બદલી શકાય.','टोकन मुफ़्त है। आगमन से 60 मिनट पहले समय बदल सकते हैं।','Tokens are free. Reschedule at least 60 minutes before arrival.')}</p><button className="btn primary full" disabled={!chosen||busy||slotsLoading||!!slotError} onClick={async()=>{if(!data.user){login();return;}const r=await post(booking.visit?'reschedule':'book',{id:booking.id,service:booking.service.id,arrival:chosen});if(r){setModal(null);setBooking(null);go('token');setMessage(t('તમારો સમય બુક થઈ ગયો.','आपका समय बुक हो गया।','Your arrival time is reserved.'));}}}>{data.user?(booking.earlier?t('વહેલો સમય સ્વીકારો','पहले का समय स्वीकारें','Accept earlier time'):t('આ સમયની પુષ્ટિ કરો','इस समय की पुष्टि करें','Confirm this time')):t('બુક કરવા સાઇન ઇન કરો','बुक करने के लिए साइन इन करें','Sign in to reserve')}</button>{booking.visit&&<button className="text-button full" onClick={()=>setModal(null)}>{t('હાલનો સમય રાખો','वर्तमान समय रखें','Keep my time')}</button>}</>}
 {modal?.kind==='confirm'&&<><h2>{modal.title}</h2><p>{modal.body}</p><div className="actions"><button className="btn" disabled={busy} onClick={()=>setModal(null)}>{t('પાછા જાઓ','वापस जाएँ','Go back')}</button><button className="btn primary" disabled={busy} onClick={async()=>{const r=await modal.run();if(r)setModal(null);}}>{t('પુષ્ટિ કરો','पुष्टि करें','Confirm')}</button></div></>}
 </dialog>{message&&<div className="toast" role="alert">{message}<button className="icon" onClick={()=>setMessage('')} aria-label={t('બંધ કરો','बंद करें','Dismiss')}><X size={16}/></button></div>}
 </div></Context.Provider>;
}
createRoot(document.getElementById('root')!).render(<App/>);
